### ISSUE TITLE
gdrive can't use now

### ISSUE THREAD

**Issue by wangxiao1021** [jinfengr/hcan#11]
The app no longer has permission to log in with a Google account.

**Comment by jinfengr** [comment]
You can download those files in download.sh via links:

collection_word_idf: https://drive.google.com/open?id=0B1EhxQ7GBJdsZTVmcFVMcDY1RWM
collection_ngram_idf: https://drive.google.com/open?id=0B1EhxQ7GBJdsbXdROGZQYzV5cFU

word2vec can be downloaded directly from Google website.

**Comment by wangxiao1021** [comment]
Thanks : )
