### ISSUE TITLE
Why the two kind of attention can solve the relevance match problem and semantic matching problem?

### ISSUE THREAD

**Issue by guotong1988** [jinfengr/hcan#3]
![image](https://user-images.githubusercontent.com/4702353/65221333-6bac3e80-daef-11e9-8843-05eb023b90a9.png)

They are all attention-based deep model.
Thank you!
@jinfengr

**Comment by jinfengr** [comment]
Please check related work on neural IR (Guo et al. 2016) and co-attention methods. Also hope my comment in the other thread can help.

**Comment by guotong1988** [comment]
https://github.com/jinfengr/hcan/issues/2
