### ISSUE TITLE
wise_encoder module's kernel_size problem 

### ISSUE THREAD

**Issue by SUNJIMENG** [jinfengr/hcan#6]
In encoder.py,  in line41, why "kernel_size=(kernel_size-1)*i+kernel_size", which is different from the paper part2.1 "Given N convolutional layers will be in [k, k+1, ..., k+N-1]."? Thanks.

**Comment by jinfengr** [comment]
@SUNJIMENG The default kernel_size is set to 2, and i refers to the i-th Conv layer (indexing starts from zero), so the kernel sizes will be in [k, k+1, ..., k+N-1]
