### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by SUNJIMENG** [jinfengr/hcan#7]
Run on TrecQA dataset, has an error as follows:
**tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[4,0] = 55604 is not in [0, 55604)**
I have checked the dict **vocab['word']**'s length is 55604, but I don't know how to debug it .Thank you very much.

**Comment by jinfengr** [comment]
can you share the command?

**Comment by SUNJIMENG** [comment]
The command is  **CUDA_VISIBLE_DEVICES=0 python -u train.py --dataset TrecQA -j hcan**

**Comment by jinfengr** [comment]
also can you share the stack trace of the error?

Also I just ran the same command as you, but didn't get any issue. Can you try with other dataset like TwitterURL?

**Comment by SUNJIMENG** [comment]
![image](https://user-images.githubusercontent.com/49275561/69526965-4a137b80-0fa6-11ea-881e-48c3f0b027fe.png)

**Comment by SUNJIMENG** [comment]
Of course, the stack trace is :
![image](https://user-images.githubusercontent.com/49275561/69527045-6c0cfe00-0fa6-11ea-9168-28f4094ec6d2.png)

**Comment by jinfengr** [comment]
Hi @SUNJIMENG can you provide me the full logs of your run? 

The above stack trace seems confirm the vocabulary index overflow issue. Also could you rerun the command to see if you can reproduce the issue as I didn't see the issue in my run?

**Comment by SUNJIMENG** [comment]
Excuse me, few days ago  I have solved it , it due to the dismatch of the tensorflow's version.
By the way, I am replicationing your model in pytorch, when I run your **train.py**,  in **evaluate** function , line 39,  it says "**permisson denied**", could you please help me ?Thank you very much.
![image](https://user-images.githubusercontent.com/49275561/70387740-d03ab380-19e3-11ea-8b75-fcd3941275cc.png)

**Comment by jinfengr** [comment]
@SUNJIMENG can you try trec_eval in a terminal manner? Similar to instructions here:

https://github.com/jinfengr/hcan/tree/master/data/twitter

**Comment by SUNJIMENG** [comment]
@jinfengr ,Sorry, I tried it in a terminal manner, I meet the same "**Permission denied**" problem.
![image](https://user-images.githubusercontent.com/49275561/70401007-b55e5280-1a68-11ea-854c-90f8f34fbb93.png)

**Comment by jinfengr** [comment]
can you try: chmod +x trec_eval?

**Comment by SUNJIMENG** [comment]
好的，谢谢您！我解决了之前的问题，我想再请教一下，源码train.py第426行用到了测试集的id.txt文件，请问训练集、验证集以及测试集中的id.txt记录的内容是什么呢？

**Comment by jinfengr** [comment]
id.txt contains unique identifier for each sample pair in the dataset. For twitter datasets, id.txt contains more rich information:
query_id, metadata, tweet_id, tweet_rank, tweet_LM_score, LM_method
